"""What the author highlighted is a retrieval signal, never rewritten text.

The operational manuals mark section titles and critical values with yellow
fills and states ("solucionado") with green — drawn by Word as filled rects
behind the text, not as /Highlight annotations. Those marks say what the
page is *about* better than any heading regex, so they join the lexical
index and the chunk metadata. The passage stored, cited and sent to the
model stays exactly what the document says — inventing text a document does
not contain is how a citation stops meaning anything.

The fixture is committed (tests/fixtures/highlighted.pdf) and regenerated by
tests/fixtures/generate.py, which hand-writes the fill ops the way Word
exports them.
"""

from pathlib import Path

import numpy as np
from qdrant_client import QdrantClient
from qdrant_client.models import (
    Distance,
    Modifier,
    SparseVectorParams,
    VectorParams,
)

from docquery.config import Settings
from docquery.ingest.chunker import Chunk
from docquery.ingest.emphasis import (
    EmphasisSpan,
    attach_emphasis,
    extract_emphasis,
    promote_emphasis_headings,
)
from docquery.ingest.loader import Document, load_document

FIXTURES = Path(__file__).parent / "fixtures"
HIGHLIGHTED = FIXTURES / "highlighted.pdf"

HEADING = "PRAZO DE QUITACAO DO BOLETO"
GREEN_LINE = "enviar o boleto ao cliente"
CPF_LINE = "Cpf do titular: 529.982.247-25"
PAGE2_HEADING = "REEMISSAO EM ATE 2 DIAS UTEIS"


def test_yellow_and_green_fill_rects_are_recovered_with_their_text():
    spans = extract_emphasis(HIGHLIGHTED)

    page1 = {(s.text, s.color) for s in spans[1]}
    assert (HEADING, "yellow") in page1
    assert (GREEN_LINE, "green") in page1
    assert (CPF_LINE, "yellow") in page1
    assert {(s.text, s.color) for s in spans[2]} == {(PAGE2_HEADING, "yellow")}


def test_decorative_slivers_are_discarded():
    """The 6x4pt rect over nothing must not become an empty span."""
    spans = extract_emphasis(HIGHLIGHTED)

    assert all(span.text for page in spans.values() for span in page)
    assert len(spans[1]) == 3


def test_page_mapped_emphasis_reaches_only_that_pages_chunks():
    doc = Document(content="", metadata={})
    doc.emphasis = {
        1: [_span("PRAZO DE QUITACAO", page=1)],
        2: [_span("REEMISSAO", page=2)],
    }
    chunks = [
        Chunk(text="p1", metadata={"page_number": 1}),
        Chunk(text="p2", metadata={"page_number": 2}),
    ]

    attach_emphasis(doc, chunks)

    assert chunks[0].metadata["emphasis"] == ["PRAZO DE QUITACAO"]
    assert chunks[1].metadata["emphasis"] == ["REEMISSAO"]


def test_without_page_provenance_emphasis_attaches_to_every_chunk():
    """The legacy loader joins pages before chunking, so provenance is gone —
    doc-level attachment is degraded but honest. Bbox refinement is a TODO."""
    doc = Document(content="", metadata={})
    doc.emphasis = {1: [_span("PRAZO", page=1)], 2: [_span("REEMISSAO", page=2)]}
    chunks = [Chunk(text="a", metadata={}), Chunk(text="b", metadata={})]

    attach_emphasis(doc, chunks)

    for chunk in chunks:
        assert chunk.metadata["emphasis"] == ["PRAZO", "REEMISSAO"]


def test_a_caps_yellow_line_becomes_a_heading_on_the_legacy_path():
    """The manuals title their sections with CAPS yellow marks, not
    "Passo N:" patterns — the highlight IS the heading signal."""
    settings = Settings(emphasis_extraction_enabled=True)

    doc = load_document(HIGHLIGHTED, settings)

    assert f"## {HEADING}" in doc.content
    assert f"## {PAGE2_HEADING}" in doc.content
    # The mixed-case CPF line is emphasized but is not a heading.
    assert f"## {CPF_LINE}" not in doc.content
    assert doc.metadata["file_type"] == ".md"


def test_flag_off_is_byte_identical():
    on_disk = load_document(HIGHLIGHTED, Settings())

    assert on_disk.emphasis is None
    assert "##" not in on_disk.content
    assert on_disk.metadata["file_type"] == ".pdf"


def test_extraction_failure_does_not_fail_ingest(monkeypatch, caplog):
    """A decoration must never fail an ingest (embedded_modified_at rule)."""
    from docquery.ingest import emphasis

    def boom(path):
        raise RuntimeError("corrupt content stream")

    monkeypatch.setattr(emphasis, "extract_emphasis", boom)
    settings = Settings(emphasis_extraction_enabled=True)

    doc = load_document(HIGHLIGHTED, settings)

    assert doc.emphasis is None
    assert HEADING in doc.content


def test_promotion_marks_only_exact_heading_lines():
    spans = {1: [_span(HEADING, page=1)]}
    text = f"intro\n{HEADING}\nbody mentions {HEADING} inline"

    promoted, changed = promote_emphasis_headings(text, spans)

    assert changed
    assert f"## {HEADING}\n" in promoted
    assert promoted.count("##") == 1


def _span(text: str, page: int, color: str = "yellow") -> EmphasisSpan:
    return EmphasisSpan(
        text=text, color=color, kind="rect", page=page, bbox=(0, 0, 10, 10)
    )


# --- Integration: terms join the sparse index, never the stored text --------

DIM = 8
COLLECTION = "test_emphasis"


def _fake_dense(texts: list[str], **_kwargs) -> np.ndarray:
    return np.tile(np.eye(1, DIM, dtype=np.float32), (len(texts), 1))


def _in_memory_client() -> QdrantClient:
    client = QdrantClient(":memory:")
    client.create_collection(
        collection_name=COLLECTION,
        vectors_config={"dense": VectorParams(size=DIM, distance=Distance.COSINE)},
        sparse_vectors_config={"sparse": SparseVectorParams(modifier=Modifier.IDF)},
    )
    return client


def _settings(**overrides) -> Settings:
    return Settings(
        qdrant_collection=COLLECTION,
        embedding_model="test/fake-embedder",
        embedding_dimension=DIM,
        **overrides,
    )


def test_emphasis_terms_join_the_sparse_index_but_not_the_stored_text(monkeypatch):
    from docquery.ingest import pipeline
    from docquery.ingest.sparse import _stable_hash

    monkeypatch.setattr(pipeline, "embed_texts", _fake_dense)
    client = _in_memory_client()
    passage = "O boleto deve ser pago em ate dois dias uteis."
    chunk = Chunk(
        text=passage,
        metadata={
            "source": "docs/manual.pdf",
            "chunk_index": 0,
            "emphasis": ["QUITACAO DO CONTRATO"],
        },
    )

    pipeline.ingest_chunks([chunk], client, _settings())

    points, _ = client.scroll(
        collection_name=COLLECTION, limit=10, with_payload=True, with_vectors=True
    )
    payload = points[0].payload
    assert payload["text"] == passage  # INV-1: the passage never changes
    assert payload["emphasis"] == ["QUITACAO DO CONTRATO"]
    assert _stable_hash("quitacao") in points[0].vector["sparse"].indices


def test_a_highlighted_cpf_is_redacted_in_the_emphasis_list_too(monkeypatch):
    """Redaction runs later in ingest_chunks and covers emphasis metadata, so
    a highlight over a CPF cannot smuggle it into the payload."""
    from docquery.ingest import pipeline
    from docquery.ingest.redact import _CPF_RE

    monkeypatch.setattr(pipeline, "embed_texts", _fake_dense)
    client = _in_memory_client()
    chunk = Chunk(
        text="Cpf do titular: 529.982.247-25",
        metadata={
            "source": "docs/manual.pdf",
            "chunk_index": 0,
            "emphasis": ["Cpf do titular: 529.982.247-25"],
        },
    )

    pipeline.ingest_chunks([chunk], client, _settings(pii_redaction_enabled=True))

    points, _ = client.scroll(collection_name=COLLECTION, limit=10, with_payload=True)
    payload = points[0].payload
    assert payload["emphasis"] == ["Cpf do titular: [CPF]"]
    assert not _CPF_RE.search(payload["text"])
